# Generated by Django 4.1.7 on 2023-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='Mr. admin', max_length=100),
            preserve_default=False,
        ),
    ]
