# Generated by Django 4.1.7 on 2023-06-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_receiver_remove_chat_sender_chat_friend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='friend',
        ),
    ]
