# Generated by Django 4.1.7 on 2023-03-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='related_project',
        ),
    ]
