# Generated by Django 4.1.7 on 2023-03-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0003_rename_project_task_related_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='supervisor',
            new_name='created_by',
        ),
    ]
