# Generated by Django 4.1.7 on 2023-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0004_rename_supervisor_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='commentOnCompletion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
