# Generated by Django 4.1.7 on 2023-03-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0005_alter_task_commentoncompletion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='commentOnCompletion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
