# Generated by Django 4.1.7 on 2023-03-31 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManager', '0008_comment_project_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='related_project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='taskManager.project'),
            preserve_default=False,
        ),
    ]
