# Generated by Django 4.1.7 on 2023-04-08 11:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0010_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=ckeditor.fields.RichTextField(default='No description provided'),
        ),
    ]
