# Generated by Django 4.1.7 on 2023-04-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0011_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='dateline',
            new_name='deadline',
        ),
    ]
