# Generated by Django 4.1.7 on 2023-04-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0012_rename_dateline_subtask_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='assigner',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='link',
            name='title',
        ),
    ]
