# Generated by Django 4.1.7 on 2023-04-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0013_rename_assigner_link_sender_remove_link_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='assigner',
            new_name='sender',
        ),
    ]
